### ISSUE TITLE
Add a persistent label aside from a placeholder

### ISSUE THREAD

**Issue by cmkramer** [basvandenberg/ng-select#106]
I'm trying to use the angular2-select as an alternative to the material2 select, which does not currently provide select2 capabilities. The component is used in forms that are built op from material style components. These components have a particular style in which the label acts as a placeholder in case no data is selected, but the label moves above the content when it is.

I would really like to be able to apply this to angular2-select as well, but that requires either the adding of an (optional) label to the component, or allowing the placeholder to be persistent.

Are you intending on facilitating such a functionality? It would really add a lot to the consistency in our implementation.

**Comment by basvandenberg** [comment]
I understand your issue, I am using material2 together with this component in some projects  as well.

The placeholder that moves to the label as soon as an input value is set, is probably not so easy to implement for this component. At this moment I have no intend to facilitate the functionality, but I might have a look at it later. It would definitely be nice to have.

My solution on material2 forms with the angular2-select form is to add a label above the angular2-select in the same style of the material2 labels (for non-empty input).

**Comment by cmkramer** [comment]
@basvandenberg I did the same for now, but you understand that it's not quite the same. There's no need to fully implement it the way they do. Just by adding an optional label attribute, which when set is placed persistently on the screen would be a great start. 

Better yet. Change the template to no longer use an *ngIf for the condition on whether or not the placeholder should be displayed. If you make it use a hidden attribute, you can default style it to "display: none" and someone like me could override your style and use a css transform to move it above the input field.

Would that not be a very quick and easy fix that doesn't break anything existing?
