### ISSUE TITLE
noOptionsFound event return null instead of search value

### ISSUE THREAD

**Issue by Moggieggwp** [basvandenberg/ng-select#109]
When I'm typing and this object is not found, the event "noOptionsFound" is triggered and call my addictional function, but how i can find something if search value = null ? I think it's must look like:
`(noOptionsFound)="search($event)"`
And will be nice if here will delay e.g. 1 sec before start searching. That's allow to user type more in input field. And anyway best way it's triggering some event for each typing, not only if options not found (with some delay). For example i have 10 persons in list. They are sorted in alphabetic. First 5 persons has surnames (A,B,C,D,E) other 5 person has same surname (F). And in database i'm also has 5 persons with surname F which don't contains in select. I make search by surname and When i'm typing "F" in search field i want to see 10 persons with family "F" but i will see 5.

**Comment by matthewhegarty** [comment]
Some kind of filter / debounce might help you.
See [SO post](http://stackoverflow.com/questions/32051273/angular2-and-debounce) for guidance.  
Posting specific code example / plunkr might help us understand the issue further.

**Comment by Moggieggwp** [comment]
http://angular-ui.github.io/ui-select/demo-basic.html
