### ISSUE TITLE
Unable to set multiple values to multiselect

### ISSUE THREAD

**Issue by pksatish07** [basvandenberg/ng-select#115]
I have a edit form where i need to bind already selected values to existing multi-select control. 
I have tried to patchValue didn't work.
this.editForm.patchValue({
            MasterData: {
                FoundBy: [2,3]
            }
        })
Since my control is in form, i'm unable to use ngmodel to bind array of data.
There is only one way mentioned in below link to set values is to create new control in ngOnInit which i cannot use because my form is already created in contructor. 
https://plnkr.co/edit/PeGmCwVmi1X8Ag7LgnPT?p=preview

How can i set  pre-selected values to multiselect control in a form in ngOnInit ?

**Comment by saithis** [comment]
@pksatish07 maybe the reason is, that you provide integers in your patchValue, but as far as I know the multiselect expects an array of strings.
Please try this: FoundBy: ['2','3']

**Comment by pksatish07** [comment]
@saithis Im getting this error. I thought it takes key. Since my key is integer i gave key. 
Anyway i tried string i still getting the error : Cannot set property 'selected' of undefined

**Comment by saithis** [comment]
@pksatish07 Can you post your template?

**Comment by pksatish07** [comment]
@saithis  below is the template .. 
//html file
<form [formGroup]="editForm" (ngSubmit)="Submit(editForm.value)">
<div class="form-group col-sm-6" formGroupName="MasterDataInfo">
<ng-select style="font-size:5px"
                                       [options]="FoundByArray"
                                       [multiple]="true"
                                       placeholder="Select Found By"
                                       formControlName="FoundBy"
                                       (opened)="onMultipleOpened()"
                                       (closed)="onMultipleClosed()"
                                       (selected)="onMultipleSelected($event)"
                                       (deselected)="onMultipleDeselected($event)" required></ng-select>
</div>
</form>

//ts file
constructor(private formBuilder: FormBuilder){
//form is created here
     this.editForm = this.formBuilder.group(
            {
                  MasterDataInfo: this.formBuilder.group({
                           FoundBy:'',
                       })
             }
}


I Have other lot of fields here in constructor
I get the data from webapi that it is to be set, which im trying to bind in ngOnInit()
ngOnInit() {
//bind data here
this.editForm.patchValue({
            MasterDataInfo: {
                FoundBy: ['2', '3']
            }
        })
}

**Comment by saithis** [comment]
@pksatish07 sorry, I can't see the html. Either try it with a code block, or upload it somewhere else and post a link here.

**Comment by matthewhegarty** [comment]
As @saithis says, you should be able to set the values using string keys (which the [angular2-select docs](https://github.com/basvandenberg/angular2-select) tell you to do).

To reach nested elements you should be able to do:

```
this.editForm.get('MasterDataInfo').get('FoundBy').setValue(['2', '3'])
```

 [This plunkr](https://plnkr.co/edit/UEHvUHyzOakZYL3Sdltw) may help.

**Comment by pksatish07** [comment]
@saithis  @matthewhegarty  Thanks a lot it worked.

**Comment by kkarandikar0807** [comment]
try this in you html
`[(ngModel]="FoundBy"`

in my case, that fixed the issue
