### ISSUE TITLE
Focus issue with multiple selections

### ISSUE THREAD

**Issue by benelliott** [basvandenberg/ng-select#119]
Thanks a lot for the library - I spent ages trawling through different select2 wrappers before finding it and it seems much better than the alternatives I tried!

I have found an issue with focus handling when the component is in multiple select mode. If a focusable element is placed before the component then that element is mistakenly activated when the Enter key is pressed to confirm a selection.

Here's a plunkr to reproduce the issue:
https://plnkr.co/edit/QsuqwKiJ1tCWCkfFYeLC?p=preview

Note the button element that is placed before the multiple selection example. When you type "0" then press enter to select the "0" value, the button will be clicked.

**Comment by ginocarrascomori** [comment]
I should be fixed if you put type="button".
Here:
<button type="button" (click)=handleButtonClick()>Some button</button>
instead of 
<button (click)=handleButtonClick()>Some button</button>

Otherwise it assumes that the button it's a submit type since it's inside of a form.

**Comment by benelliott** [comment]
You're totally right, thanks!
