### ISSUE TITLE
Allow for setting the filter placeholder

### ISSUE THREAD

**Issue by Crevil** [basvandenberg/ng-select#121]
Would be great if it was possible to set the filter input placeholder possibly through an input.
Something like:

```html
<ng-select filterPlaceholder="Type something"></ng-select>
<ng-select [filterPlaceholder]="somePlaceholderProperty"></ng-select>
```

Currently I'm doing a nasty hack traversing the DOM to get this set.

**Comment by basvandenberg** [comment]
PR is merged into beta.4 branch.
