### ISSUE TITLE
Allow disabling of browser autocomplete

### ISSUE THREAD

**Issue by cmkramer** [basvandenberg/ng-select#126]
It would be great if the input could disable browser autocomplete. Right now this often results in a double dropdown. One facilitated by the browser, through browser autocomplete, and one by the directive.

Could you either always set the autocomplete attribute of the input field to "off", or allow passing it as an optional attribute for the directive so a dev can determine whether or not they want it to be applied?

**Comment by basvandenberg** [comment]
My preference would be to disable this by default, I don't see any advantage in having an autocomplete on the filter input field. I'll have to look around a bit for a cross-browser solution for this.

**Comment by cmkramer** [comment]
Great!
