### ISSUE TITLE
Rename module to be just Angular

### ISSUE THREAD

**Issue by Crevil** [basvandenberg/ng-select#127]
The module name `angular2-select` is not meaningful anymore as Angular has switched to semantic versioning, i.e. on any breaking change the major version (2) will become (3).

To follow the Angular recommendations, see the [Press Kit](https://angular.io/presskit.html) on brand names, I propose the module be renamed to `angular-select`.

The [NPM module name](https://www.npmjs.com/search?q=angular+select) is available so the switch could be made fairly pain free.

As long as the module is in a beta state, this could be the right time to do the switch before a stable release. It could as well be possible to make a deprecation periode where the module is available on both names but with a warning on the deprecated one.

**Comment by basvandenberg** [comment]
Thanks for raising this. It seems that angular-select is already taken. Instead I claimed ng-select on npm for now. The difficult part will be migrating without too much pain...

I also see that I should not use a component selector starting with ng-, which I am doing currently...

**Comment by basvandenberg** [comment]
Renamed to ng-select. Hopefully I covered everything, it was pretty painless process, so probably I overlooked something important :) We'll see.

**Comment by Crevil** [comment]
GJ! Thanks for the quick responses and maintanence of this repo.
