### ISSUE TITLE
ngModel not work in 1.0.0-beta.3

### ISSUE THREAD

**Issue by SMAH1** [basvandenberg/ng-select#130]
OS: Ubuntu 16.04 - X64
@angular/cli: 1.0.0-rc.0
node: 7.6.0
os: linux x64
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8
@angular/upgrade: 2.4.8
@angular/cli: 1.0.0-rc.0

I update from 1.0.0-beta.2 (angular2-select) to 1.0.0-beta.3 (ng-select).
I use component like:
```
<ng-select
  name="cbxGroup"
  [options]="groupsList"
  [(ngModel)]="selectedGroupValue"
  (selected)="onGroupChanged($event.value)"
  class="fnt_imp"
></ng-select>
```

When I set value to 'selectedGroupValue', no selected in component.

I downgrade to 1.0.0-beta.2, All is work.

**Comment by basvandenberg** [comment]
This [example](https://basvandenberg.github.io/ng-select/#value) still works with `ng-select` version `1.0.0-beta.3`. Can you show the behavior with a plunkr maybe?

**Comment by GuillaumeNury** [comment]
The problem is that the `ng-select` is not initialized with the `ngModel` value.
As you show in your plunker, the property in `ngModel` is correctly updated when something is selected.

Here is a plunker : [LINK](https://plnkr.co/edit/oX4BOtkBSaI46YOLHM5W?p=preview)

**Comment by simon-kunz** [comment]
I had the same issue. My problem was that the options where fetched from the server and were not available at the time the model was bound. The solution was to set the options before the model value.
I have not dug deeper but it seems that ng-select resets the value when no matching option is present.
Hope this helps...

**Comment by basvandenberg** [comment]
In the upcoming beta.6 it will be possible to set the value before setting the options. This should solve the issue.
