### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by Hi4mRaj** [basvandenberg/ng-select#133]
How do we achieve validation?

**Comment by Hi4mRaj** [comment]
let c: FormControl = new FormControl('', Validators.required);
    this.userForm.addControl('rolesSelected', c);

When do the above validation works but the error message is there on form loading itself.

**Comment by basvandenberg** [comment]
You could use the touched property for showing only after the select component has been touched. See also the "_Use the select component with a reactive form_" [example](https://basvandenberg.github.io/ng-select/).

**Comment by Hi4mRaj** [comment]
Hi basvandenberg,

Thank you for your quick reply. I am using the form.valid to deactivate the submit button to achieve the validation at the moment.

If I submit my empty form, all the text fields with Validators.required are prompting message (default message I guess ) 'Please fill out this field' one after another. But that is not the case with ng-select. 

Please advise.
