### ISSUE TITLE
Beta 3 cannot pre populate select box if options are retrieved using Observer

### ISSUE THREAD

**Issue by SachinSharmaEarthport** [basvandenberg/ng-select#135]
Hello there,

I have a number of options that are retrieved using an Observer when accessing a web service.  Once they are retrieved from the web service I set the selected options.  However on my web page the selected options are not being set and the value is empty with the placeholder string as shown in the screenshot:

![image](https://cloud.githubusercontent.com/assets/24301036/23669670/db2785b6-035c-11e7-8a1f-e3fb6b43d09d.png)

Here is my code below:

HTML:

 ```
                <ng-select
                        [multiple]="true"
                        [options]="bankAccountOptions |orderBy : ['label']"
                        [placeholder]="'Select a Bank Account...'"
                        [(ngModel)]="selectedBankAccounts"
                        name="bankAccount">
                </ng-select>
```

Here is the Angular code called on ngOnInit() to get the bank account from a web service and pre populate the select box with the choices.

```
    getBankAccounts():void {
        this.bankAccountService.getBankAccounts()
            .subscribe(
                bankAccounts => {this.setBankAccountOptions(bankAccounts); this.setSelectedBankAccountIDs()},
                error => this.errorMessage = <any>error
            );
    }
```

As shown above after the data is retrieved from the service the select box is populated with options by calling 'this.setBankAccountOptions(bankAccounts)'.,  Here is the code for this:

```
    private setBankAccountOptions(bankAccounts:BankAccount[]) {
        let options = new Array();

        for (let bankAccount of bankAccounts) {
            options.push({value: bankAccount.bankID.toString(), label: bankAccount.description});
        }
        this.bankAccountOptions = options;
    }
```

Then after this the selected options are set in   'setSelectedBankAccountIDs()':

    setSelectedBankAccountIDs() {
        if(this.bankAccountOptions == null || this.model.bank_accounts == null) return;

        this.selectedBankAccounts = new Array();
        for (let bankAccount of this.model.bank_accounts) {
            this.selectedBankAccounts.push(bankAccount.id.toString());
        }
        console.log('Selected bank accounts = ' + this.selectedBankAccounts);
    }

It seems that when populating the options array and setting the selected option asynchronously with Observable and subscribe this issue happens.  This happens for single and multi select boxes.  I first noticed this issue happening on beta 3.  This problem was not happening on beta 1 or 2.  

I tried to recreate the issue in plunkr but was getting typescript errors I could not resolve.  Here it is if interested using a simple example of simulating numbers returned from a web service https://plnkr.co/edit/pa7PQudFl1gsmjzLEgkY?p=info .

Can you advise please?

Kind Regards,

Sachin Sharma

**Comment by usego** [comment]
I see the similar issue there...

`<ng-select #ddlDep [options]="departmentsDropdown" (selected)="departmentSelected($event)" placeholder="-- select department --" [(ngModel)]="activeDepartment" name="department"></ng-select>`

Dropdown doesn't select activeDepartment after options are populated. But it works if activeDepartment is set later by setTimeout(() .... , 3000) or by clicking button like in example.

**Comment by tsengkhai** [comment]
For me I'm using *ngIf to do the trick

<ng-select [options]="bankAccountOptions" *ngIf="bankAccountOptions"></ng-select>

bind the component only if the data variable has a value.

**Comment by basvandenberg** [comment]
If you change the list of options, angular needs some time to detect that an input value of the ng-select component has changed. There for setting a value right after this does not work. An often-seen solution to this issue is to set the value inside a `setTimeout` without a delay as below:

```typescript
getBankAccounts() {
    this.bankAccountService.getBankAccounts().subscribe((bankAccounts) => {
        this.setBankAccountOptions(bankAccounts);
        setTimeout(() => {
            this.setSelectedBankAccountIDs();
        });
    
    }, (error) => {
        // ...
    });
}
```

Hopefully that helps. Please let me know if this works.

**Comment by SachinSharmaEarthport** [comment]
Thank you for that.  This works by setting the timeout.
