### ISSUE TITLE
Prevent the dropdown from closing when a result is selected

### ISSUE THREAD

**Issue by MehdiSaeedifar** [basvandenberg/ng-select#137]
Please Add [this feature](https://select2.github.io/options.html#can-i-prevent-the-dropdown-from-closing-when-a-result-is-select) to this grate library.

**Comment by yousharizvi** [comment]
So an optional `autoClose` config parameter you're suggesting right?

**Comment by MehdiSaeedifar** [comment]
Yes, especially for multi select.

**Comment by yousharizvi** [comment]
Please help this PR in merging, this is the solution to your issue.
`autoClose: boolean` will work in all cases either for multiple or single select.

**Comment by yousharizvi** [comment]
@MehdiSaeedifar please have a look on this PR and verify

**Comment by brulejr** [comment]
Any update on this issue? Did it actually make it into the 1.0.0-beta.6 release?

**Comment by yousharizvi** [comment]
I'm back on this, will update the PR soon
