### ISSUE TITLE
How can I change the font  ?

### ISSUE THREAD

**Issue by rannaot** [basvandenberg/ng-select#138]

**Comment by rannaot** [comment]
in General I solved it like this for my specific scenario, 
 <ng-select class="myFont"
                [options]="foodUnits"
                [noFilter]="10"
                [ngStyle]="{'width': '190px'}">
            </ng-select>

.myFont>ng-select > div > div.single > div.value, ng-select > div > div.single > div.placeholder{
  font-family: 'my font family here';
}

why did you specify font family btw? maybe better to inherit...

**Comment by Crevil** [comment]
You could set it with CSS:

```css
ng-select div, ng-select li {
  font-family: monospace;
}
```

**Comment by basvandenberg** [comment]
Thanks for answering @Crevil. I hope that helps you out @rannaot. I will close the issue.
