### ISSUE TITLE
Create item on the fly

### ISSUE THREAD

**Issue by OlivierCroisier** [basvandenberg/ng-select#140]
When the text entered as a filter does not match any of the predefined items, pressing Enter should create a new item on the fly (with an undefined id) and notify the parent component.

Possible options:
* Ability to create new items on the fly (boolean)
* Case-sensitivity during the "filter text / item" matching process 
* ID of the newly created items (maybe "undefined" by default, but a configurable value would be helpful)

**Comment by basvandenberg** [comment]
Duplicate #105 

This feature will not be added in release 1.0.0.
