### ISSUE TITLE
Breaks Testing With Karma

### ISSUE THREAD

**Issue by CreamFraiche** [basvandenberg/ng-select#141]
When testing a component using this component with Karma, It does not allow the page to be queried by queried as so: de = fixture.debugElement.query(By.css('div')); Having the select component on the page breaks the query and DE returns null, not allowing one to  get its native element.

**Comment by basvandenberg** [comment]
I am not sure if this is an issue in the ng-select component. Why would the select component break the query `By.css('div')`. Could you give a code example?

**Comment by CreamFraiche** [comment]
sorry
