### ISSUE TITLE
Filter display should be togglable regardless of option list size

### ISSUE THREAD

**Issue by tiagoroldao** [basvandenberg/ng-select#148]
Presently, [noFilter] is a number representing the limit over which a filter box should be displayed.
This means there is no way to disable it completely (barring setting it to an unreasonably large number)

Possible solutions:
- interpret a value of `-1` to mean "always off, as `0` means "always on"
- allow for `[noFilter]` to be a number or a boolean. If a non number value, its truth value is checked instead of comparing to list size

A PR can be presented to fix this, but it would build on #147 and depend on the preferred strategy to use

**Comment by basvandenberg** [comment]
This can be achieved by setting the value to [`Infinity`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity) 

I will add this to the example/documentation.

**Comment by tiagoroldao** [comment]
True, but it is still semantically confusing - I'd consider `Infinity` to qualify as "an unreasonably large number" 😄
