### ISSUE TITLE
Consider adding https://basvandenberg.github.io/ng-select in repo's description

### ISSUE THREAD

**Issue by tytskyi** [basvandenberg/ng-select#152]
There is no reachable demo link nor on repo nor in readme file. 

Therefore potential user needs to check if there is a `gh-pages` branch and then construct url manually.

Thank you.

**Comment by basvandenberg** [comment]
The first sentence of README contains a link to the demo page:

> A select component for angular, based on the select2 JQuery plugin. See the [ng-select](https://basvandenberg.github.io/ng-select/) page for example uses or try it with this plunker.
