### ISSUE TITLE
Change dropdown colors

### ISSUE THREAD

**Issue by mohitook** [basvandenberg/ng-select#153]
Hello,

Is it possible to change the colors of the dropdown? 
I have tried it many ways but I can't access it through css classes.. not even when I'm trying like:
```
#midCol > div.panel-heading > h4 > ng-select > select-dropdown > div {
    background-color: #a94442;
}
```

could you provide me any solution? The white dropdown doesn't really fit in my page, neither the blue heighlight..

**Comment by mval1002** [comment]
`select-dropdown > div .options` - For unselected
`select-dropdown .highlighted` - For hover
`select-dropdown .selected` - For selected

`background-color` and `color` both worked on each of these selectors without a problem for me

**Comment by mohitook** [comment]
@mval1002 
Unfortunately only the focused (.highlighted) and selected works, but I will change the dropdown background color itself.. and the .options doesn't work :(

**Comment by mval1002** [comment]
Hmmm... I checked them all before posting. I guess it's possible that you have other CSS rules causing a conflict?

Also, note the space after `> div` - `.options` is a child of that, so if you leave out the space it wont work. 

I would also try adding `!important` to your rules. While it's generally frowned upon to use it, it's helpful in finding if there are other selectors overriding what you expect, or if you have the wrong selector altogether.

**Comment by basvandenberg** [comment]
The style rules proposed by @mval1002 work for me as well, I don't think this an ng-select issue. If you need help getting your CSS to work, please use something like stackoverflow.
