### ISSUE TITLE
Add a typed event to update the options list

### ISSUE THREAD

**Issue by hantsy** [basvandenberg/ng-select#154]
Currently I can not find a way to update the options list according to the typing text in the filter input box. 
If possible to add an event to  watch user input?

eg. 

```
typed(e){
  console.log('event typed:' + e.typedText);
  this.options= this.someSerivce.get(e.typedText);// return an Observable
}
```

**Comment by basvandenberg** [comment]
There is a  `noOptionsFound` [output event](https://github.com/basvandenberg/ng-select#output-events) that returns the user input text if no options were found for that text.
