### ISSUE TITLE
Drop down closes when clicking a disabled option

### ISSUE THREAD

**Issue by vishalborker897** [basvandenberg/ng-select#156]
In case a option is disabled using {value: "1", label: "1", disabled: true} then in the UI the element should have cursor: not-allowed, and also it should not be allowed to select. Currently default cursor is shown and item is allowed to select(problem) but value is not set (which is awesome).

**Comment by basvandenberg** [comment]
Hello @vishalborker897, thanks for reporting this. 

Currently the selectable options have a 'pointer' cursor and the default options a 'default' cursor. The styling clearly indicates that the option is disabled. This is exactly the same as the disabled options in the [select2](https://select2.github.io/examples.html#disabled-results) jQuery plugin and also in line with many other components. Therefore I don't want to use the 'not-allowed' cursor for disabled options.

The disabled options cannot be selected, but clicking them causes the drop down list to be closed, which is wrong indeed. This is a bug, I will have a look at that. Thanks again!

**Comment by basvandenberg** [comment]
Will be fixed in upcoming beta.6 release. Thanks for reporting @vishalborker897!
