### ISSUE TITLE
Odd display using form-group and form-control

### ISSUE THREAD

**Issue by jmls** [basvandenberg/ng-select#157]
When putting ng-select into a form-group, I get the following

![image](https://cloud.githubusercontent.com/assets/929523/25070271/0c6b49ec-2292-11e7-8423-a6502c3d3bb9.png)

The relevant html is
```html
                    <div class="form-group col-xl-6">
                        <label for="summary">Summary</label>
                        <input type="text" class="form-control" name="summary" id="summary"/>
                    </div>

                    <div class="form-group col-xl-6">
                        <label for="type">Task Type ()</label>
                        <ng-select [options]="types" class="form-control" name="type" id="type" ></ng-select>
                    </div>
```
what am I missing ? ;)

**Comment by Crevil** [comment]
The bootstrap `form-control` class is not delegated into the `ng-select` styles. You should style the `ng-select` component to you likings explicitly.

**Comment by jmls** [comment]
thanks for the update - but from what I can tell ng-select adds another div in - hence the increase in size I can't remove that can I ?

I suppose I could look at mucking around with the margins / padding and removing any borders . Will try that

**Comment by Crevil** [comment]
Yeah, you should style it to your likings. Bootstraps `form-control` class is for styling `input` elements or wrapping `div` elements only. Not for complex components like this one.

**Comment by peteythefool** [comment]
have you gotten around the problem?
I'm about 5 minutes away from making a jQuery function to inject the `form-control` class into the div inside `<ng-select>`.

**Comment by peteythefool** [comment]
Ok, so i got it working, you can't use the component specific CSS file, for some reason, the whole shadow DOM thing don't seem to work for the `<ng-select>` element,  so here's what you have to do:
-Create a "global" CSS file that you include in index.html file;
-Select the element using `ng-select > div `, and add the styling of the regular `form-control` class;
-Pat yourself in the back, and go get more coffee/tea.

**Comment by basvandenberg** [comment]
The components view encapsulation is set to None: 
```typescript
    encapsulation: ViewEncapsulation.None
```
which means that the shadow DOM is not used for this component. This is done because of many requests for styling this component from external CSS files.
