### ISSUE TITLE
How to use with async data

### ISSUE THREAD

**Issue by aucevica** [basvandenberg/ng-select#160]
I've been studying Angular 2 with Firebase for a short time.

I reading the data using AngularFire2 observables and I want to populate the array passed to NG-SELECT component asynchronously? 

Is there any ASYNC option?

**Comment by basvandenberg** [comment]
The list of select options are bound to an Array in your component class. You can load your options (asynchronously) and then set those as select options Array, these options will then automatically show up in your select drop down.

See also these [examples](https://basvandenberg.github.io/ng-select/#options).
