### ISSUE TITLE
Select Options not updating

### ISSUE THREAD

**Issue by mslicee** [basvandenberg/ng-select#165]
First off I am pretty new to Angular 4. I am trying to update the options array after doing an API call in the ngOnInit() method. Now the data is being retrieved and pushed in the options array however the select does not update the options.

`<ng-select [options]="venueList" [multiple]="false" placeholder="Event Venue" formControlName="venue" (selected)="getVenueAddress($event.value)" [allowClear]="true">
                </ng-select>`

That is how I am initializing the Select in the HTML.

Any help would be greatly appreciated.

**Comment by basvandenberg** [comment]
If you want the options to be updated, you'll need to replace the option array with a new one, so that angular detects that it is a new object. If you push new options to existing list of options, angular will not detect that change, which is why the new options will not appear in the select drop down.

This won't work:

``` typescript
ngOnInit() {
    // Set option list.
    this.venueList = [];

    // Load venues.
    this.venuesService.loadVenues().subscribe((venues) => {
        venues.forEach((venue) => {
            // This doesn't work. The array venueList remains the same object, angular 
            // will not detect a change within the object.
            this.venueList.push(venue);
        });
    });
```

This will work:
``` typescript
ngOnInit() {
    // Set option list.
    this.venueList = [];

    // Load venues.
    this.venuesService.loadVenues().subscribe((venues) => {
        // This will work. Now the venueList is replaced with a new array, which
        // will be detected by angular.
        this.venueList = venues;
    });
```
