### ISSUE TITLE
ng-untouched class does not change after selection of an option value in IE Browsers

### ISSUE THREAD

**Issue by aleemlatif** [basvandenberg/ng-select#168]
ng-untouched class stays as ng-untouched in IE Browsers after making any selection of an option value.

"ng-select": "^1.0.0-beta.5",

**Comment by basvandenberg** [comment]
Can you give a code example? Or a plunkr?

I cannot test this in IE now, so could you maybe check if the touched behavior works for the 'Use the select component with a reactive form' on the [examples page](https://basvandenberg.github.io/ng-select/)?

**Comment by basvandenberg** [comment]
The (un)touched behavior has been updated, should work in beta.6 (beta.6 is not yet released, that will still take some time).
