### ISSUE TITLE
Why type of value must be string?

### ISSUE THREAD

**Issue by leovo2708** [basvandenberg/ng-select#171]
Hi, I am using your component.
I check IOption interface
```
export interface IOption {
    value: string;
    label: string;
    disabled?: boolean;
}
```

I don't know why type of value must be string. I think it should be any to apply number or enum or any types I want. Thanks.

**Comment by basvandenberg** [comment]
This already has been discussed before, see alse #87 #89 #108 

Since the value is used as option identifier, it must be a primitive type (string, number) in my opinion (see comments in referenced issues). Strings in my opinion make most sense, for now I'll stick to that.
