### ISSUE TITLE
Cannot GET /node_modules/ng-select/dist/select.component.html,because of  html.js

### ISSUE THREAD

**Issue by dfostic** [basvandenberg/ng-select#172]
Unhandled Promise rejection: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/node_modules/ng-select/dist/select.component.html

version installed:  ng-select@1.0.0-beta.5

there are no html or css files in /dist/ directory, only html.js and css.js

It may be a bug
 ### I was able to make it working changing **select.component.js** & **select-dropdown.component.js**:
```
var select_component_css_1 = require("./select.component.css");
var select_component_html_1 = require("./select.component.html");
to 
var select_component_css_1 = require("./select.component.css.js");        // added .js
var select_component_html_1 = require("./select.component.html.js");   // added .js

and **select-dropdown.component.js**
var select_dropdown_component_css_1 = require("./select-dropdown.component.css");
var select_dropdown_component_html_1 = require("./select-dropdown.component.html");
to
var select_dropdown_component_css_1 = require("./select-dropdown.component.css.js");        // added .js
var select_dropdown_component_html_1 = require("./select-dropdown.component.html.js");   // added .js
```

**Comment by basvandenberg** [comment]
I'll need more information about how you installed/use the component. Do you use angular-cli for your project?

I haven't seen any similar issues yet, so my guess is that this is not a ng-select bug. I will close the issue for now. Please let me know if you have more information, or if you're sure that this is a bug, then I will reopen the issue.
