### ISSUE TITLE
Control becomes dirty when using ngModel and model was changed NOT by the user

### ISSUE THREAD

**Issue by Deilan** [basvandenberg/ng-select#176]
Control becomes dirty when using `[(ngModel)]` and the model being bound to was changed NOT by the user (for example loaded asynchronously from the remote server).
As per [Angular documentation](https://angular.io/docs/ts/latest/guide/reactive-forms.html):

> `pristine` - `true` if the user has not changed the value in the UI. Its opposite is `dirty`.

[Plunker demo](https://plnkr.co/edit/K668VsBwnXmt9O80jihb?p=preview) (inspect the `ngOnInit`method)

**Expected**:
After 2 seconds the following text line appears in preview:
`is form pristine: true`

**Actual:**
After 2 seconds the following text line appears in preview:
`is form pristine: false`

**Why it's important?**
It is very common to disable submission of the form based on status of the `dirty`/`pristine` property of it. This isssue breaks such a logic.

**Comment by basvandenberg** [comment]
This should be fixed in the upcoming beta.6 release. Thanks for reporting!
