### ISSUE TITLE
Multiselect is not updated when user use form.patchValue method

### ISSUE THREAD

**Issue by tomasznastaly** [basvandenberg/ng-select#179]
Hey:
In this plunker i reproduced the error:
https://plnkr.co/edit/rQ3LGwFH9NRpsyRGi6t8?p=preview

When i use this.form.patchValue({ ... }), then multiselect is not correctly updated. Please look at "remove(index)" method.

any idea how to fix that bug?
best Regards,
Tomasz

**Comment by basvandenberg** [comment]
Deselecting options with `patchValue` seems to work, but I guess you mean that the deselected event is not triggered in this case? I'l have a look at that. Thanks for reporting.

**Comment by angularlove** [comment]
thanks for answer, i have already fixed it, now plunker works correctly. What was bad - i used splice(index,1) on form.numbers.value and then copy that. Good solution in firstly copy the value from model, and use splice. 

So it's not bug. We can close this topic, thank you
