### ISSUE TITLE
Problem with select value

### ISSUE THREAD

**Issue by shulolo** [basvandenberg/ng-select#180]
Hi,

I'm writting you because I have a problem with default selection on ng-select.

In my component, I fill an Array of IOption on a suscriber.
This array is used on a ng-select in my HTML template.
In my ng-select I have also a ngmodel attribute, with a string array as a value.
And in the suscriber, I fill also this string array with the value of the element that I want to be selected on the ng-select.

The problem is that it does not work inside the suscriber, the element is not selected, but  if I fill my array of IOption outside the suscriber, it works, the element is selected.

So I would like to know if we can do that inside the suscriber? If it is possible, How can I do that?

Thank you in advance.

**Comment by basvandenberg** [comment]
Something like this should work.

```typescript
mySelectOptions: Array<IOption>; // ng-select [options]
mySelectValue: string; // ng-select [(ngModel)]

ngOnInit() {
    this.optionsService.loadOptions().subscribe((options) => {
        // Set the list of options.
        this.venueList = venues;
        // Set your default value.
        setTimeout(() => {
            this.mySelectValue = '2';
        });
    });
}
```
The `setTimout` is required because otherwise angular would not have detected the changed list of options yet. I am trying to update the ng-select so that this won't be needed in the next release (beta.6) anymore.

I hope this helps, let me know if you have further questions.

**Comment by shulolo** [comment]
Thank you for your response.
In fact this is what I have done for the moment, and it works. 
So I will continue to use waiting for the next release :)

Thank you again.
