### ISSUE TITLE
CSS of element

### ISSUE THREAD

**Issue by shulolo** [basvandenberg/ng-select#181]
Hi,

This is me again :)

I'm writing you because I would like to change the display of the element of my ng-select.
I know that we can override CSS of the entire ng-select, but what I want is to change the CSS of the element which are on the ng-select.
For example, I would like underline some of my elements, make others bold.
I looked on the IOption interface but I did not find how to do that.

Is there a way to do that, or should I change the source code (which I do not no for the moment if it will work, if I change it)?

Thank you in advance.

**Comment by basvandenberg** [comment]
Hi @shulolo,

You can modify the styling using CSS, but there are limitations. For convenience, there are the 'style' options for setting the highlight background and text color. For the rest you'll have to define your own CSS rules.

I am sorry, but this is more a support question. Please use stackoverflow or similar fora with questions like this. This is for reporting issues.
