### ISSUE TITLE
Import style and template

### ISSUE THREAD

**Issue by unlight** [basvandenberg/ng-select#184]
I'm working with own webpack configuration (not angular-cli)
How this should be handled?
```
import {STYLE} from './select.component.css';
import {TEMPLATE} from './select.component.html';
```
It's not ES2015 modules.

It fails with errors:
```
Expected 'styles' to be an array of strings.
Error: No template specified for component 
```

Consider to replace above constructions to:
```
const STYLE = require(./select.component.scss').toString();
const TEMPLATE = require('./select.component.html').toString(); // or without toString()
```

**Comment by basvandenberg** [comment]
Source files are being post-processioned in the build process (`gulp build`), see the build file ([gulpfile.js](https://github.com/basvandenberg/ng-select/blob/master/gulpfile.js)).
