### ISSUE TITLE
ngModel not work when load dynamically options

### ISSUE THREAD

**Issue by SMAH1** [basvandenberg/ng-select#185]
After update from angular2-select to ng-select

![bug1](https://cloud.githubusercontent.com/assets/21136680/26819327/a1f01f58-4ab3-11e7-892a-765a1802b4e0.png)

in html
`<div class="field">
          <div class="control">
            <span class="is-fullwidth">
              <ng-select
                name="cbxGroup"
                placeholder="Select one of the characters"
                [options]="groupsList"
                [(ngModel)]="selectedGroupValue"
                (selected)="onGroupChanged($event.value)"
                class="fnt_imp"
              ></ng-select>
            </span>
          </div>
        </div>`

and in ts
`
this.groupsList = groupsList;
this.selectedGroupValue = this.selectedGroup.id;
`

I fix it by replace line
`this.selectedGroupValue = this.selectedGroup.id;`
by
`setTimeout( ()=>{
        this.selectedGroupValue = this.selectedGroup.id;
      }, 100);`

**Comment by basvandenberg** [comment]
Duplicate #130 #169 

Is fixed, the `setTimeout` won't be needed anymore in the upcoming beta.6 release.

The 100ms delay is not needed by the way, the following should be sufficient:
```typescript
setTimeout(()=>{ this.selectedGroupValue = this.selectedGroup.id; });
```
