### ISSUE TITLE
Noobie question

### ISSUE THREAD

**Issue by DiscoDancer** [basvandenberg/ng-select#186]
Hello everyone.
How can I update options of select?
I use array of IOptions to initialize, but then I need to push/splice items. Simple performing this operations gives me no result.
PS Seriously, what is wrong with it? I do the same with HTML select all works fine.

**Comment by MStoehr** [comment]
Afaik this is due to Angular2 Change Detection not detecting changes on arrays which get pushed/spliced. 
You have to reinitialise the array to trigger  the change detection.

For example, I am using http-requests to fill my data. Whenever I get new data (e.g. by auto-refresh), I do something like this:
`class dataComp{
optList: IOption[]  = [];

function getDate() {
   http.get('dummyUri').subscribe(data => {
      this.optList = []; //this is the important part
         data.forEach(e => {
             //do some stuff with the data
             this.optList.push(e)
          })
       })
   }
}`

**Comment by DiscoDancer** [comment]
@MStoehr Thanks. I tryied this again and it works fine.

**Comment by DiscoDancer** [comment]
@MStoehr In that case, if I reinitialise the array, my selected option (selection) will dissapear? If so, then I surely can manually set selection after it, but it will lead to bad user experiese, won't it?
BTW in pure HTML <select> I don't have to reinitialise.

**Comment by MStoehr** [comment]
Yes, if you do it the way I suggested in my comment, you will not have your selection anymore. 
For my usecase that doesn't really matter, so I just set the selection afterwards. You could disable the select-box until your data is loaded to prevent actions while updating, but I don't know if that fits your needs. 

Afaik you don't have to use a forEach-loop or any loop at all. 

```
class dataComp{
optList: IOption[]  = [];

function getData() {
   http.get('dummyUri').subscribe(data => {
      this.optList = []; //this is the important part
         this.optList = data;
       })
   }
}
```
This should detect the changes as well and it might be a bit faster (I think), although it doesn't solve the selection-problem. 

I know, but Angular2's change detection works different, I think. I ran into issues with that a few times.

**Comment by basvandenberg** [comment]
Angular's change detection only detects a different object (if you have an array and then push items to it, it is still the same array object, only the content has changed, it would be very expensive if angular would constantly have to check if the content of an object has changed). Therefore to update the list of options you'll need to have your bound options variable point to a new Array object. 

Having your `optList` variable point to the new `data` Array should be sufficient for angular to detect the change, and update your list of options in the select drop down.

```typescript
class dataComp{
    optList: IOption[]  = [];

    function getData() {
        http.get('dummyUri').subscribe(data => {
            this.optList = data;
        })
    }
}
```
I hope that clears things up a little.
