### ISSUE TITLE
Add style to inner div of ng-select

### ISSUE THREAD

**Issue by SMAH1** [basvandenberg/ng-select#187]
I try add icon to ng-select like this
![2](https://user-images.githubusercontent.com/21136680/26866423-495a0a0c-4b76-11e7-9c81-4324e05040d2.png)
but view this
![1](https://user-images.githubusercontent.com/21136680/26866441-58091034-4b76-11e7-8b64-da0dd50d2d6c.png)
I hack css and insert padding to div.single!
suggest:  Define style property in ng-select for add padding, ... to master inner div

**Comment by basvandenberg** [comment]
You can now use an option template for showing an icon. See the ng-select website https://basvandenberg.github.io/ng-select for option template documentation and examples.
