### ISSUE TITLE
Suggestions for quicker use/ Issue with focus-event

### ISSUE THREAD

**Issue by MStoehr** [basvandenberg/ng-select#188]
I've started using ng-select a day ago and I found some things that I'd like to have in it. 

1. There might be an issue with the "focus" event in this. I've tried to tab through some selects and open then by hitting "return". I found that this only worked every second time. 

2. I think it would be awesome if the value gets selected as soon as you mark it (e.g. by using arrow keys), as I am using the selects for filtering. By now (in chrome), when you use arrow keys, you need to hit "return" to select the value. I want this not in the openend state of the select, but when it's focused, just like the "normal" html-select does work.

3. This one is focus-related, too. I'd like to be able to use the arrow keys as soon as the select is focused instead of only when it is opened. I think that would made it "quicker" to use by tabbing through, using arrow keys (therefore the selection part above) and filtering that way.

I know that this is very specific to my own usecase, so I'd understand if you don't agree with my suggestions.

**Comment by basvandenberg** [comment]
Hello @MStoehr , thanks for your comments. In future, please report different issues/request in separate issues. That makes it a lot easier to track and discuss things.

About point 1: I'll need a concrete example to see if this is a bug and when exactly it occurs.

About points 2 and 3: Correct me if I'm wrong, but these points the same right? Being able to 'scroll' through the options with the up/down array keys when the select has focus but the drop down is still closed. This would only make sense for the single select off course. I like that idea, but it does not have priority at the moment, so if this would be implemented, this would not be soon.

**Comment by basvandenberg** [comment]
Focus seems to work as expected in beta.6.
