### ISSUE TITLE
noFilter property does not reflect data 

### ISSUE THREAD

**Issue by rebeencom** [basvandenberg/ng-select#190]
noFilter property should reflect the returned data. EX: I set noFilter = 10, so the filter will be hidden when array length is less than 10. But when the array update to over 10 items, the filter still hidden,  not make sense. It also happen if the returned data is decreased less than the limit number, the filter still show. :(

**Comment by basvandenberg** [comment]
Duplicate #146, is fixed in beta.6 branch with #147.
