### ISSUE TITLE
How to preselect dropdown with array of selected values coming from json service.

### ISSUE THREAD

**Issue by shamanth7077** [basvandenberg/ng-select#191]
I need to auto select items from the dropdown on pageload with an existing selected list coming from the service call. Is this feature supported?

**Comment by shamanth7077** [comment]
I went through some of the closed issues and saw by adding a settimeout it can be acheieved.
setTimeout(()=>{ this.selectedAuthorsListField = [3] }, 100);

But directly assigning to ngmodel without settimeout does not work.

**Comment by basvandenberg** [comment]
The 100ms delay is not needed, just the setTimeout should work, this is explained in the closed issues:
```
setTimeout(()=>{ this.selectedAuthorsListField = [3] });
```

In the upcome beta.6 release this won't be necessary anymore. Also directly assigning ngModel will work in beta.6.

**Comment by basvandenberg** [comment]
Beta.6 is released.
