### ISSUE TITLE
Change detection of placeholder attribute is ignored.

### ISSUE THREAD

**Issue by marekozw** [basvandenberg/ng-select#192]
```html
<ng-select [options]="myOptions" [placeholder]="myPlaceholder">
```

```javascript
@Component({
  selector: 'my-component'
})
class MyComponent {
  public myPlaceholder: string = 'initial placeholder';

  public onMyButtonClick(): void {
    this.myPlaceholder = 'other value than before'; // WILL NOT WORK
  }
}
```

It is impossible to update placeholder attribute because of `placeholderView` variable. This variable is getting updated only when `model` or `options` changes. So changing "placeholder" attribute is totally ignored.

It is very troublesome because it is impossible to use translations (e.g. ngx-translate) or any other logic that requires dynamic changes of this attribute.

Current workaround:

1. Make sure `this.myOptions` has initial value of an empty array.
`this.myOptions: object[] = [];`
2. Force change `options` variable when `placeholder` needs to be updated:
```javascript
this.myPlaceholder = 'other value than before';
this.myOptions = [ ...this.myOptions ]; // WORKAROUND
```

Full snippet:

```javascript
@Component({
  selector: 'my-component'
})
class MyComponent {
  public myPlaceholder: string = 'initial placeholder';
  public myOptions: object[] = [];

  public onMyButtonClick(): void {
    this.myPlaceholder = 'other value than before';
    this.myOptions = [ ...this.myOptions ]; // placeholder update triggered manually.
  }
}
```

**Comment by basvandenberg** [comment]
Thanks for reporting @marekozw . I switched to using a placeholderView variable, which should be updated when the input placeholder changes (this input property was used directly before, so there was no need to explicitly handle a changing placeholder value). I'll add a placeholder change handler to fix this issue.
