### ISSUE TITLE
Placeholder is not visible 

### ISSUE THREAD

**Issue by vishnunair17** [basvandenberg/ng-select#193]
Hello, 

I have added the placeholder text to "ng-select" like it was mentioned in the docs,

```ts            
<ng-select
       [options]="options"
       [multiple]="true"
       placeholder='My Placeholder'
       formControlName="control_name">
</ng-select>

```

However the placeholder does not show up initially, the select itself is working fine with the dropdown and all but the placeholder remains blank until I select some options from the dropdown and then remove them all at this point the placeholder text in the attribute shows up. Not sure what's wrong..

**Comment by vishnunair17** [comment]
Well turns out the ng-select's input element had an initial width of just 1px which is why the placeholder wasn't visible, once an option was selected the width increased and hence it was visible later on. I couldn't update the style/css of the input element using `[ngStyle]` I had override the style block in my `style.css` to make it work, 

```css
ng-select > div > div.multiple input{
	width:100% !important;
	height:50px;
}
```

**Comment by basvandenberg** [comment]
In which web browser is this? The [placeholder examples](https://basvandenberg.github.io/ng-select/#text) work fine for me.

The width of the input is dynamically updated in the code, it should be set to a larger width if there is a placeholder, question is why this did not happen in your case.

**Comment by vishnunair17** [comment]
It was the same for me in all Browsers, Chrome, Firefox etc. My form(with ng-select) is sitting inside a Bootstrap modal anything to do with that? since modal is hidden initially, wide guess.

**Comment by transparentech** [comment]
I am also seeing this behaviour using Chrome and Safari. Adding the css from vishnunair17 in my style.css fixed it.

**Comment by basvandenberg** [comment]
There is a reason that the input width is dynamically updated. Because if you select an option with a fixed 100% width input, then the input will go underneath the selected options, thereby unnecessarily expanding the height of the select container.

I would very much like to understand what is going wrong in your situation, because in all my test cases it works as expected. Can you provide a code example or maybe a plunkr?

**Comment by transparentech** [comment]
Here's a test repo with an example:

https://github.com/transparentech/ng-select-test

It a default angular-cli (v1.1.2) app with the addition of ng-select (1.0.0-beta.5) and bootstrap (4.0.0-alpha.6). 

Checkout the project, then run 'npm install' then 'ng serve' and look at http://localhost:4200  There should be a placeholder in the ng-select, but it doesn't show until you add-remove a tag.

**Comment by basvandenberg** [comment]
Are you sure that you push your commits to the ng-select-test? I only see two commits, one with initial angular-cli commit, and one with an added package-lock.json file.

**Comment by basvandenberg** [comment]
Thanks for reporting, this is indeed a bug in beta.5. Without realizing before, another bug fix and some refactoring have already resolved this issue in beta.6 (not yet released).

**Comment by transparentech** [comment]
Great. Thanks for verifying. Any ETA on when beta.6 will be released?

**Comment by omairaslam817** [comment]
By setting <ng-select> property from [multiple]="false" to [multiple]="true" ,placeholder will be show at initially also,that works for me.
