### ISSUE TITLE
Pre-selected do not appear with observables and reactive forms.

### ISSUE THREAD

**Issue by Tolitech** [basvandenberg/ng-select#194]
Hello.

When I'm using the component in both single or multi-mode, the initial records that should have been pre-selected are not displayed in ng-select.

The insert works perfectly.
However, the initial load (pre-selection editing a record) does not appear.

If I simply change `<ng-select>` to `<select>` html, everything works fine.
The records are selected.

For other select components they work as well.
Apparently it's a bug in the component, because the values are being passed correctly for the formControl.

Even if I pass hard code values by the formControl, it is still showing in `<select>,` but does not show in `<ng-select>.`

`this.formGroup = this.fb.group({`
`     categories: [[1, 3, 4]]`
`});`

I am using observables and reactive forms, as per the code below.

Any idea?
Thank you.

Bug image:
[http://www.codegenerator.com.br/images/bug.png](http://www.codegenerator.com.br/images/bug.png)

### HTML

`<ng-select formControlName="categories" [options]="selects.categories" [multiple]="true"></ng-select>`
`<select formControlName="categories" multiple>`
`     <option *ngFor="let item of selects.categories" [value]="item.value">{{ item.label }}</option>`
`</select>`

### TS

`this.formGroup = this.fb.group({`
`     categories: [((this.categories && this.categories.map((x) => { return x.id; })) || [])]`
`});`

`this.categoryService`
   `.get()`
   `.takeUntil(this.ngUnsubscribe)`
   `.subscribe(items => {`
      `this.selects.categories = items.map(x => { return { value: x.id, label: x.category }; });`
`});`

**Comment by basvandenberg** [comment]
Duplicate #130 #169 #180 #191 

Currently (beta.5) you cannot select an option as long as the list of options is not set. This is fixed but not yet released (will be in beta.6).

**Comment by Tolitech** [comment]
That's right.
If I use setTimeout as workaround it works correctly.
I'll wait for the new version.
Thank you.

**Comment by basvandenberg** [comment]
Beta.6 is released.

**Comment by Tolitech** [comment]
Thanks, but now i have a new problem.
The same code now display:

Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked.

`
<select [(ngModel)]="grid.filters.idStatusCategoria" multiple>
            <option *ngFor="let item of grid.selects.itemsStatusCategoria" [value]="item.value">{{ item.label }}</option>
</select>
`

it works perfectly.

But:

`
<ng-select [(ngModel)]="grid.filters.idStatusCategoria" [options]="grid.selects.itemsStatusCategoria" [placeholder]="'shared.input.select' | translate" [notFoundMsg]="'shared.input.selectNotFound' | translate" [multiple]="true"></ng-select>
` 

It does not work anymore.

**Comment by Tolitech** [comment]
I was able to figure out the problem.
It refers to the placeholder.
I'm going to open a new issue.
