### ISSUE TITLE
Updating the optionList from Rest Service 

### ISSUE THREAD

**Issue by raoghuge** [basvandenberg/ng-select#195]
I have a rest service which returns data which I am pushing to OPTION_LIST. But this does not update in the UI.
Declaration:
`OPTIONS_BASIC: Array<IOption> = [];`
In constructor, I am loading the data from server. 
```
 this._authService.getOptions('username').subscribe(
            d => {
                for (let party of this.allOptions) {
                this.OPTIONS_BASIC.push( {value: party.companyName, label: party.displayName});
              }
            },
            err => { console.log(err.json()); }
          );
```
But this does not update the list. I browsed all the reported issues here, but did not get any solution. Please refer me to some link, docs to do the same.

**Comment by basvandenberg** [comment]
Duplicate #165 . My answer to that issue explains how to update the list of options.

**Comment by raoghuge** [comment]
Thanks. It's resolved now.
