### ISSUE TITLE
edit page set default value by selected have an error

### ISSUE THREAD

**Issue by AbbyXiong** [basvandenberg/ng-select#196]
because of my value type is  number
so have an error:zone.js:522 Unhandled Promise rejection: Value must be a string or an array. 
set: function (v) {
            if (typeof v === 'undefined' || v === null || v === '') {
                v = [];
            }
            else if (typeof v === 'string') {
                v = [v];
            }
            else if (!Array.isArray(v)) {
                throw new TypeError('Value must be a string or an array.');
            }
            if (!option_list_1.OptionList.equalValues(v, this._value)) {
                this.optionList.value = v;
                this.valueChanged();
            }
        },
anyone could help add a else if type is number.

**Comment by Gillardo** [comment]
got this problem as well. What was your fix?
