### ISSUE TITLE
Cannot bind complex model

### ISSUE THREAD

**Issue by topguss** [basvandenberg/ng-select#197]
There is problem when I try to bind complex object (propertie form object) e.g.
`<ng-select [options]="options" [(ngModel)]="organization.organizationType" ></ng-select>`.

First of all, there is generic error: 

> Error: Uncaught (in promise): TypeError: Value must be a string or an array.
But organizationType is string.

And the second it seams that If I use delayed binding (loading options via services), then select value become empty. (test case when I add simple property to bind on it).

**Comment by basvandenberg** [comment]
Could you provide (part of the) component class code? To see why `organization.organizationType` is not accepted for value binding?

The delayed binding issue is reported in several other tickets. This has been fixed in beta.6, but has not been released yet.

**Comment by basvandenberg** [comment]
Please test in beta.6 and re-open issue if the problem remains (with example code please).
