### ISSUE TITLE
With angular-cli ng-select's CSS is added after application's Css

### ISSUE THREAD

**Issue by transparentech** [basvandenberg/ng-select#200]
I want to override some of the CSS from ng-select.

However, ng-select's CSS is added as the last "<style>" tag in the html head section. This means my CSS changes, which I put in angular-cli's src/style.scss file, are overridden by ng-select's defaults.

Is there a way to override the CSS?

**Comment by Jalrom** [comment]
Did you try adding !important?

My styles.css looks as follows:
`ng-select .below {
  border-radius: 4px !important;
}`

This should make the borders of the select field rounder.

**Comment by transparentech** [comment]
Adding !important would probably work, but I was hoping to just be able to swap out CSS completely. I've seen other plugins which allow you to disable the inclusion of the CSS (see this one https://www.npmjs.com/package/ng2-select2) and thought that would be useful here.

**Comment by transparentech** [comment]
Basically, I'm using this along with Bootstrap 4. I'd like to get ng-select to look the same as the other bootstrap 4 input fields.

So I'd like to either 1) have full control over the CSS or 2) have full control over the CSS classes included on the elements (perhaps like it's possible with the option template).

**Comment by basvandenberg** [comment]
This is not a regular input field, so the bootstrap 4 CSS would not have the desired effect. You will have to modify the CSS yourself to achieve this. As @Jalrom pointed out, you can use !important, but I guess making your CSS rules more specific should also overrule the component's CSS.

```css
your-app ng-select>div {
    border-radius: 4px;
}
```
In which `your-app` is the tag name of your web application (I didn't test this though).
