### ISSUE TITLE
Validation triggered automatically

### ISSUE THREAD

**Issue by Jalrom** [basvandenberg/ng-select#203]
Hello,

My select fields seem to detect value changes before I even do anything.

I created a form using the form builder.
      `this.formGroup = this.fb.group({
            country: [this.country, [Validators.required ]]
       });`

I subscribe to valueChanges of the form group.
        `this.formGroup.valueChanges.subscribe(() => this.onValueChanged());`

My field should only activate its required message if it is invalid and dirty. (Same as the example in the reactive form validation in the angular cookbook).

On AfterViewInit, the field using ng-select is already dirty even if I did not touch it, causing my error message to appear  and valueChanges have been detected although I don't do anything.

When using the regular select of angular2, everything works fine.

Any help would be appreciated, thank you.

**Comment by Jalrom** [comment]
As a temporary solution I clear all errors in ngAfterViewInit.

**Comment by basvandenberg** [comment]
For which version is this? I think this has been fixed in beta.6. See also the reactive form example on https://basvandenberg.github.io

**Comment by Jalrom** [comment]
I was using version 1.0.0-beta.2 of angular2-select.
I just updated to 1.0.0-beta.3 and it works fine.
Thank you for this!

**Comment by basvandenberg** [comment]
The component has been renamed to ng-select and is currently at version beta.6.
