### ISSUE TITLE
No EventEmitter for filter input

### ISSUE THREAD

**Issue by Makiah** [basvandenberg/ng-select#209]
This is an extremely important function for those who wish to update the dropdown options as the filter is changed, and to my knowledge, no such functionality currently exists.

**Comment by Gillardo** [comment]
This is what i have been looking for in this component, but i guess it doesnt exist yet.  Would love to use this component, but feel i cant without this functionality as all of our data is loaded once a filter is typed

**Comment by moser96** [comment]
@Makiah @Gillardo  There is a possibilty to react for changed input. I'm using the solution mentioned in https://github.com/basvandenberg/ng-select/issues/46 and it's working fine for me 😄

**Comment by Makiah** [comment]
Great idea!  Hadn't realized that to be a possibility.
