### ISSUE TITLE
Group multiple item

### ISSUE THREAD

**Issue by masoudline** [basvandenberg/ng-select#213]
hi
how can i group multiple item with ng-select?

i have 20 provinces that each provinces has 40 city!

please add this feature to your component!

please help me!

also i read this issue: #55 but noting exists in that

**Comment by masoudline** [comment]
is anybody here?

**Comment by basvandenberg** [comment]
Not if you use that many exclamation marks...

This is indeed already reported in #55. 

For me this doesn't have high priority, so I did not plan to include this in the 1.0 version. Also, when searching a big list of options using a filter, then I don't really see the point in organizing this list into groups (maybe only if the filter also applies to the group names...).
