### ISSUE TITLE
How to override message "No results found" ?

### ISSUE THREAD

**Issue by MrHOY** [basvandenberg/ng-select#215]
I want to set message when no results, how can I do this ?

**Comment by basvandenberg** [comment]
By setting the `notFoundMsg` property to the text you want to show:
```html
<ng-select
    notFoundMsg="No characters found"
    [options]="characters">
</ng-select>
```
Please stick to reporting issues here. Use Stackoverflow or a similar forum for asking quentions. And consult the [documentation](https://basvandenberg.github.io/ng-select), you could have found it there as well.
