### ISSUE TITLE
ngModel for Multiple instances in a single page

### ISSUE THREAD

**Issue by arinhere** [basvandenberg/ng-select#219]
Hi,

I need to use multiple instances of multi select in a single page and in the loading, I need to assign different selected values to each of them.

So for example, in dropdown1, i needed to show Alabama, Houston and in dropdown2, i needed to show Boston, LA. These selected data will be set from DB. 

Do you have any suggestion regarding this matter? Please let me know

Thanks in advance

**Comment by basvandenberg** [comment]
You can have as many select components on a single page as you want, each bound to a different list of options and to different variables that hold the currently selected value. 

For questions, please use something like stackoverflow, this is for reporting issues.
