### ISSUE TITLE
Focus/Blur & Open/Close

### ISSUE THREAD

**Issue by lucasjaviluna** [basvandenberg/ng-select#224]
Hi, is possible have a way to open the select when it gets the focus, and close it when it's blur.
I tried with timeouts but not lucky. It seems there are some "colition" between focus and click andkeydown events.
Also, in IE11 is not working as expected. When the select is open, you press shift + tab and nothing happens.

**Comment by basvandenberg** [comment]
You could try to call the 'open' method when the `focus` output event is triggered, but I haven't tried that myself.

For me shift+tab seems to work as expected in IE11.
