### ISSUE TITLE
Changing border-radius

### ISSUE THREAD

**Issue by msegmx** [basvandenberg/ng-select#225]
Hello,

I use bootstrap, and bootstrap has rounded corners on all input elements.
Is there a way to style ng-select to have rounded corners ?

I tried this in component.css but it has no effect :
```
ng-select {
    border-radius: 5px;
}
```

**Comment by msegmx** [comment]
ok, you already answered this in previous posts.
Still, I'll leave this here, maybe it will help somebody.

in component.css :

```
ng-select > div.below {
    border-bottom-right-radius: 5px;
    border-top-right-radius: 5px;
}

ng-select > div.open {
    border-bottom-right-radius: 0px;
    border-top-right-radius: 5px;
}

```

and in component.ts :
```
@Component({
  selector: 'app-selectbox',
  templateUrl: './selectbox.component.html',
  styleUrls: ['./selectbox.component.css'],
  encapsulation: ViewEncapsulation.None
})
```

Or :

simply put the css solution from above in global css file.

Thanks for this great component !

**Comment by msegmx** [comment]
@basvandenberg : There are times I need to add a class via [ngClass]={'has-error': booleanValue} .

when I simply add the class="form-control" to the ng-select directive I get unwanted result, as in selectbox inside textbox, meaning the actual selectbox gets a border and shrinks.

Would you consider adding a ngClass directive that would add/remove to the first div, (div.below to be precise) ?

**Comment by msegmx** [comment]
Solved it by changing the selector :
```
ng-select.has-error >div.below {
	border: 1px solid #a94442;
}
```

I'll leave it here for other developers.

**Comment by basvandenberg** [comment]
Closing this issue, because it doesn't seem to be an issue. Thanks for posting your solutions here for other developers.
