### ISSUE TITLE
Width and position of dropdown menu

### ISSUE THREAD

**Issue by sommcz** [basvandenberg/ng-select#227]
Hello,

is there any way how to set position of opened dropdown? I need to center it along with the ng-select element.

Another thing - i want to set width of menu do different size (base on content), width: 100% set with CSS works fine. Is it right way to to this?

thank you
p.

**Comment by basvandenberg** [comment]
The dropdown should always have the same width as, and be aligned with the ng-select. So why do you need to center it along with the ng-select element?

You can change the width by changing the CSS width of the ng-select element, that's the right way to do that. The dropdown should then have the same width.

**Comment by sommcz** [comment]
I need different apperance (i'm converting contemporary design based on jquery select2 to ngx), where dropdown has different width than ng-select element (i did this by CSS), but centering couldn't be done the same way - you position it to the left (maybe this default postioning could be changed to center - it will work fine for both same and different widths).

The only option now, is to find raw DOM elements (as angular elements in ng-select components are private and i cannot access them directly in component (ViewChild(SelectComponent)) and resize it after ng-selects positioning.

Do you want this feature or its unwanted?

thank you
ps.
