### ISSUE TITLE
How can you set this control to required?

### ISSUE THREAD

**Issue by Gillardo** [basvandenberg/ng-select#228]
Setting [required] doesnt seem to work.  I am using this as a component around my site, not just in 1 place and need to be able to set it to required using a varaible.

In ngx-bootstrap, there is a [required] property which can be used.

**Comment by basvandenberg** [comment]
Please check the "Documentation"  [here](https://basvandenberg.github.io/ng-select), there you can see that there is no `required` input property for this component.

On the same web site, on the "Examples -> Form validation" page, you can see how you can use a required validator in a reactive form.
