### ISSUE TITLE
Filter options based on another dropdown using pipe

### ISSUE THREAD

**Issue by gieboyz** [basvandenberg/ng-select#230]
Hi basvandenberg,
im using your library, and i think it's good. but i still have problem to implement **filter options based on another dropdown**

here is my logic 
```
let obj1 = [
{ value: 1, label: 'a'},
{ value: 2, label: 'b'},
{ value: 3, label: 'c'},
]

let obj2 = [
{ value: 1, label: 'child_label_a', val_obj1: 1},
{ value: 2, label: 'child_label_a', val_obj1: 1},
{ value: 3, label: 'child_label_a', val_obj1: 1},
{ value: 4, label: 'child_label_b', val_obj1: 2},
{ value: 5, label: 'child_label_c', val_obj1: 3},
]

what i want to expect is, if i select dropdown with value = 1 dropdown 2, will show like this
let obj2 = [
{ value: 1, label: 'child_label_a', val_obj1: 1},
{ value: 2, label: 'child_label_a', val_obj1: 1},
{ value: 3, label: 'child_label_a', val_obj1: 1}
]
```
can you  provide it ?..

**Comment by basvandenberg** [comment]
Hello @gieboyz, 

To achieve this you can change the list of options that is bound to your second ng-select if the first ng-select changes.

Use the `selected` output event of your first ng-select to figure out what option is selected, and based on that replace the list of options that is bound to your second ng-select.

**Comment by raysuelzer** [comment]
I have also been attempting to do this, and have been running into an issue with infinite looping.  You cannot use a filter pipe on the options because it causes ng-select to infinitely re-evaluate the pipe... I will post my solution here when I figure it out.

**Comment by martinduris** [comment]
Hi,
is there solution how to use pipe for array used in [options]

`example: [options]="myArrat | filterBy: 'A'"`

Thanks !
