### ISSUE TITLE
cannot set the default value

### ISSUE THREAD

**Issue by jusfeel** [basvandenberg/ng-select#231]
In my case, I am binding to a property of an object. The default value cannot be set.

    <ng-select 
        name="eventDataCode" 
        id="eventDataCode" 
        [options]="codeList" 
        placeholder="" 
        [(ngModel)]="eventData.event.code" required ></ng-select>

    ngOnInit() {

        this.eventData = new EventData;
        this.eventData.event.code = "abc";
        console.log(this.eventData.event);// code:undefined
        console.log(this.eventData.event.code);// code:abc
    }

**Comment by kajdzo** [comment]
Hi @jusfeel I have the same issue, did you by any chance managed to resolve it? Thanks.

**Comment by jusfeel** [comment]
Yes. Just make the this.eventData.event.code javascript 'object'. "string" won't work.
