### ISSUE TITLE
Angular 5 Support

### ISSUE THREAD

**Issue by readme42** [basvandenberg/ng-select#242]
As Angular 5 is in release candidate phase now, it would be great if this library would be compatible. 
Currently the deprecated `ngOutletContext`, which was removed in angular 5, breaks this.

**Comment by xavierclotet** [comment]
Can you commit to master ? I want to upgrade to angular 5 wich recently came out.

**Comment by mikejf-pr** [comment]
The package changes now list angular 5 as required rather than just compatible; is this the case? ngTemplateOutletContext should exist in ng4 as well.
