### ISSUE TITLE
Getting `ERROR TypeError: Value must be a string or an array` when binding to [formControlName]

### ISSUE THREAD

**Issue by resting** [basvandenberg/ng-select#254]
I need to generate the dropdown component dynamically. When trying to bind the `formControlName`, it throws `ERROR TypeError: Value must be a string or an array.`

See the console of https://stackblitz.com/edit/angular-6z4n2b?file=app%2Fdrop-down%2Fdrop-down.component.html

Removing the line `[formControlName]="config.name"` fixes the error, but I need to bind it to the control to get the values.

Any idea whats wrong?

**Comment by renilbabu03** [comment]
Facing the same issue

**Comment by art-mickiewicz** [comment]
I had the same issue. The reason is: you have values of number type while IOption requires string:
```
interface IOption {
    value: string;
    label: string;
    disabled?: boolean;
}
```

I think this could be better if ng-select handled the conversion self. Like this:
```
    set value(v) {
        if (typeof v === 'undefined' || v === null || v === '') {
            v = [];
        }
        /* Convert number to string */
        else if (typeof v === 'number') {
            v = [v + ''];
        }
        else if (typeof v === 'string') {
            v = [v];
        }
        else if (!Array.isArray(v)) {
            throw new TypeError('Value must be a string or an array.');
        }
        this.optionList.value = v;
        this._value = v;
        this.updateState();
    }
```

So IOption could have value of type string|number.

**Comment by resting** [comment]
Realised this issue is still open, here's some of my findings for people with the same issue.

First, check that `value` and `label of options is `string` mentioned above.
Check that you're not passing anything when creating the formControl like `new FormControl()`.

I found that I could fix the error by simply leaving the function call empty.

`this.config.forEach(control => group.addControl(control.name, this.fb.control()));`
from 
`this.config.forEach(control => group.addControl(control.name, this.fb.control({})));`

https://stackblitz.com/edit/angular-ssytfs?file=app%2Fdynamic-form%2Fdynamic-form.component.ts

**Comment by danilocgraciano** [comment]
Hi,

I'm have been the same problem related by art-mickiewicz, in my case the problem happens when the model.id is integer, but the options generated by my option list have to be string, using the ngModel directive.

So, using the solution proposed here the values are converted automatically from int to string, and works fine.

`<div class="form-group required" formGroupName="pais">
    <label class="control-label" for="pais">País</label>
    <ng-select formControlName="id" [options]="paisList | options : 'id' : 'descricao'"[(ngModel)]="municipio.pais.id" [allowClear]="true">
    </ng-select>
  </div>`

It would be a greate help if the author implements this new feature for us.

**Comment by luis-guzman-datum** [comment]
Lo solucione de la siguiente manera

this.myOptions.push({ label: label, value: value+'' });
