### ISSUE TITLE
NgModel does not update ngSelect value

### ISSUE THREAD

**Issue by vugar005** [basvandenberg/ng-select#260]
Hi .I have 
html:

```
<ng-select
    [options]="myOptions"
   [(ngModel)]="selectedProperty"
  placeholder="Choose your country"
>
</ng-select>
```
TS:
```
 myOptions: Array<IOption> = [
        {label: 'Austria', value: 'AU'},
        {label: 'Luxembourg', value: 'LU'},
        {label: 'Germany', value: 'GR'}
    ];
selectedProperty: string;
```

By default if no option selected placeholder will be show as label. 
1. If I choose Austria the 'selectedProperty' value will be 'AU' and ng-select label 'Austria'
2. Then I want to manually change selected value by below code
`"this.selectedProperty = 'LU'"` so it is expected to have 'Luxebbourg' as label in ng-select BUT what I see is
the ng-select label  changed from 'AU' to default placeholder('Choose your country') .What is wrong? Hope someone give advice.Thanks in advance.

**Comment by basvandenberg** [comment]
The following in your component
```
this.selectedProperty = 'LU';
```
should work fine. I don't think this is an bug in the ng-select component. If you need help with using the ng-select component, please use stackoverflow or something similar.

**Comment by vugar005** [comment]
the problem is 2way data binding does not work with string. I changed to arrays and it worked as expected.

`this.selectedProperty = ['LU'];`

**Comment by basvandenberg** [comment]
That is the difference between single-select and muli-select. With single select you should use:
```
this.selectedProperty = 'LU';
```
With multiple select you need to use a list (because you can select multiple items):
```
this.selectedProperty = ['LU'];
```
or
```
this.selectedProperty = ['LU', 'GR'];
```
See also the ngModel [example page](https://basvandenberg.github.io/ng-select#/examples/ng-model)

**Comment by vugar005** [comment]
I fixed the 2way databinding in single-select with by using arrays. Otherwise it wont synchronize. I keep using array for single and multiple select to solve the problem. Thanks anyway.
