### ISSUE TITLE
Is it possible to modify the value of filter/selected value on blur?

### ISSUE THREAD

**Issue by resting** [basvandenberg/ng-select#262]
I don't think that's possible now, could use some ideas how to make it possible by changing the source.

Use case is when user enters `430` in the filter box, I want to auto format it as `04:30` on blur or `enter`.

#46 might be a possible work around, but it should ideally be `onBlur` or `selected` event.

**Comment by basvandenberg** [comment]
There is a blur event, see [documentation](https://basvandenberg.github.io/ng-select#/documentation) (Output events section) and [example](https://basvandenberg.github.io/ng-select#/examples/focus). And there is a selected event as well.
