### ISSUE TITLE
this.dropdown.hostElement.nativeElement.firstChild.getBoundingClientRect is not a function

### ISSUE THREAD

**Issue by grubby14** [basvandenberg/ng-select#287]
I encountered the following problem:
     each click ng-select pop-up drop-down menu is console error : this.dropdown.hostElement.nativeElement.firstChild.getBoundingClientRect is not a function and delete an option prompt error: cannot read property 'hostElement' of undefined.
hope someone can help me! 
thanks

**Comment by mjacobson7** [comment]
I'm seeing this as well, although, everything seems to be functioning as it should from a user perspective. Is that the case for you as well?

**Comment by basvandenberg** [comment]
Duplicate #286. [Fix](https://github.com/basvandenberg/ng-select/commit/2f262e39855b8264f2191d94d1b4f082bc5adf2a) already in place for next release
