### ISSUE TITLE
DOM is not getting reflected if [option] value is changed

### ISSUE THREAD

**Issue by monis01** [basvandenberg/ng-select#294]
Hi 
I have a list and on submit I want to remove the item from the list. I am keeping the selected item index and on submit I just splice it, but it is not being reflected back in DOM. for e.g. 
```
<ng-select  (selected)="storeIndex($event)"  [options]="theList"></ng-select>
```
```
public theList = [{value:'1',lablel:'a'},{value:'2',lablel:'b'},{value:'3',lablel:'c'},{value:'4',lablel:'d'}]
onSublit(){
this.theList.splice(0,1); //@ it get's update here but not reflected in DOM
}
```
It will still show all the list in ng-select. Why it can be, am I missing something here ?

PS: I have written just small code snippet for query purpose only.

Thanks

**Comment by basvandenberg** [comment]
Angular change detection checks if the object (by reference) has changed, not if the content of your object has changed. Please check out this [faq](https://basvandenberg.github.io/ng-select#/faq) question. I hope that helps, let me know if you need more help.

**Comment by monis01** [comment]
Thanks it worked now
