### ISSUE TITLE
[disabled] option doesn't work

### ISSUE THREAD

**Issue by arkonbob** [basvandenberg/ng-select#297]
I have tried adding the option [disabled]="true" to an ng-select as shown here: 

[(https://ng-select.github.io/ng-select#/multiselect)]

However I receive the following runtime error in the browser console:

`Can't bind to 'disabled' since it isn't a known property of 'ng-select'.
`

I would like to use the option on a single select if possible, but I have tested on both a single and multi select and it doesn't work in either case. Other options work as expected.  I am using v0.35.1

**Comment by basvandenberg** [comment]
The URL you provided is from another [ng-select](https://github.com/ng-select/ng-select) component, which is currently at v0.35.1. Please report your issue there.
