### ISSUE TITLE
Binding not working anymore

### ISSUE THREAD

**Issue by meiuqer** [basvandenberg/ng-select#298]
So i didn't change anything about my code but i did update to a more recent version of ng-select and now when i change something the ng-select stays empty up until i click something, probably the next change detection that happens. I'm talking about the [ngModel] binding.

I tried looking for something that changed, but couldn't immediately find something. Maybe i overlooked something? Sorry if this question has been asked before.

Angular version:
angular/cli: 1.0.3
node: 6.11.1
os: win32 x64
angular/common: 4.1.2
angular/compiler: 4.1.2
angular/core: 4.1.2
angular/forms: 4.1.2
angular/http: 4.1.2
angular/platform-browser: 4.1.2
angular/platform-browser-dynamic: 4.1.2
angular/router: 4.1.2
angular/cli: 1.0.3
angular/compiler-cli: 4.1.2

Ng-select:
"ng-select": "^1.0.0-rc.3",

Sample code:

HTML: 
```
<ng-select [options]="options" [ngModel]="value" (ngModelChange)="emit($event)"
    [placeholder]="placeholder">
</ng-select>
```
Typscript: 

```
import { Component, Input, Output, EventEmitter, OnChanges, OnInit, ChangeDetectionStrategy } from '@angular/core';

@Component({
    selector: 'cv-select',
    templateUrl: './select.component.html',
    styleUrls: ['./select.component.css'],
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class SelectComponent implements OnInit, OnChanges {
    @Input() public options: any;
    @Input() public value: any;
    @Input() public placeholder: string;
    @Output() public valueChange = new EventEmitter();

    public firstChange: boolean = true;

    constructor() {
    }
    ngOnChanges(changes) {
    }
    ngOnInit() {
    }
    convertArray(array) {
    }
    emit(event) {
        this.valueChange.emit(this.value);
        this.firstChange = false;
    }
}
```
`options` is always in the format of `{ label: string, value: string}[]`.
`value` is always a string

**Comment by basvandenberg** [comment]
> now when i change _something_ the ng-select stays empty up until i click _something_,
It's a bit difficult to understand what can be wrong here, 'something' can be anything really :)

Did you try this with the most recent version already? Do you still have the same issue?

**Comment by meiuqer** [comment]
Yeah i think it's a version issue. Havent had the chance to upgrade cause working on a very big project and updating is not without consequences
