### ISSUE TITLE
Angular 4 support

### ISSUE THREAD

**Issue by mikejf-pr** [basvandenberg/ng-select#300]
Requrements/packages for this were updated to angular 5 some time ago, replacing the depricated ngOutletContext with ngTemplateOutletContext.

The change as implemented listed angular 5 as a hard requirement rather than being compatible with 4 and 5. ngTemplateOutletContext exists in angular 4 as well as 5, and should allow for a graceful upgrade rather than having to big bang change our own app ng version at the same time as we upgrade ng-select. Is it possible to support package compatibility with both?

**Comment by basvandenberg** [comment]
Peer dependencies includes Angular4 in the latest release.
