### ISSUE TITLE
SelectOnTab not working 

### ISSUE THREAD

**Issue by shuaib786** [basvandenberg/ng-select#314]
[selectOnTab] | `boolean` | `false` | no | Select marked dropdown item using tab. Default `false`| 
Is not working .It has rensering issues

**Comment by ManojRamanan** [comment]
+1 I am also facing the same issue

**Comment by basvandenberg** [comment]
I think you posted this issue in the wrong repository. This ng-select component does not have a `selectOnTab` option.

**Comment by shuaib786** [comment]
But selectOnTab is on the ngselect javascript library

**Comment by shuaibabdulla** [comment]
Hi ,

this.on('keypress', function (evt) {
var key = evt.which;

  if (self.isOpen()) {
    if (key === KEYS.ESC || key === KEYS.TAB ||
        (key === KEYS.UP && evt.altKey)) {
      self.close();

      evt.preventDefault();
    } else if (key === KEYS.ENTER) {
      self.trigger('results:select', {});

      evt.preventDefault();
    } else if ((key === KEYS.SPACE && evt.ctrlKey)) {
      self.trigger('results:toggle', {});

      evt.preventDefault();
    } else if (key === KEYS.UP) {
      self.trigger('results:previous', {});

      evt.preventDefault();
    } else if (key === KEYS.DOWN) {
      self.trigger('results:next', {});

      evt.preventDefault();
    }
  } else {
    if (key === KEYS.ENTER || key === KEYS.SPACE ||
        (key === KEYS.DOWN && evt.altKey)) {
      self.open();

      evt.preventDefault();
    }
  }
});
};

Could you plesae provide the feature of
if (key === KEYS.ESC || key === KEYS.TAB ||
(key === KEYS.UP && evt.altKey)) {
self.close();

      evt.preventDefault();
    }
as
else if (key === KEYS.ENTER) {
self.trigger('results:select', {});

      evt.preventDefault();
    }
on one small new attribute selectOnTab = true

@shuaibabdulla
 
Author
shuaibabdulla commented 36 seconds ago • 
The code changes needed is
this.on('keypress', function (evt) {
var key = evt.which;

  if (self.isOpen()) {
    if (key === KEYS.ESC || key === KEYS.TAB ||
        (key === KEYS.UP && evt.altKey)) {
     `
self.trigger('results:select', {});

`

      evt.preventDefault();
    } else if (key === KEYS.ENTER) {
      self.trigger('results:select', {});

      evt.preventDefault();
    } else if ((key === KEYS.SPACE && evt.ctrlKey)) {
      self.trigger('results:toggle', {});

      evt.preventDefault();
    } else if (key === KEYS.UP) {
      self.trigger('results:previous', {});

      evt.preventDefault();
    } else if (key === KEYS.DOWN) {
      self.trigger('results:next', {});

      evt.preventDefault();
    }
  } else {
    if (key === KEYS.ENTER || key === KEYS.SPACE ||
        (key === KEYS.DOWN && evt.altKey)) {
      self.open();

      evt.preventDefault();
    }
  }
});
};

**Comment by shuaibabdulla** [comment]
The code changes needed in core.js is 
this.on('keypress', function (evt) {
      var key = evt.which;

      if (self.isOpen()) {
        if (key === KEYS.ESC || 
            (key === KEYS.UP && evt.altKey)) {
          self.trigger('results:select', {});

          evt.preventDefault();
        } 
		`**else if (key === KEYS.ENTER || key === KEYS.TAB)**` {
          self.trigger('results:select', {});

          evt.preventDefault();
        } else if ((key === KEYS.SPACE && evt.ctrlKey)) {
          self.trigger('results:toggle', {});

          evt.preventDefault();
        } else if (key === KEYS.UP) {
          self.trigger('results:previous', {});

          evt.preventDefault();
        } else if (key === KEYS.DOWN) {
          self.trigger('results:next', {});

          evt.preventDefault();
        }
      } else {
        if (key === KEYS.ENTER || key === KEYS.SPACE ||
            (key === KEYS.DOWN && evt.altKey)) {
          self.open();

          evt.preventDefault();
        }
      }
    });
  };
