### ISSUE TITLE
Text input - Cannot read property 'replace' of null

### ISSUE THREAD

**Issue by caleuanhopkins** [basvandenberg/ng-select#318]
```
ERROR TypeError: Cannot read property 'replace' of null
    at Function.push../node_modules/ng-select/fesm5/ng-select.js.Diacritics.strip (ng-select.js:66)
```

When I type into the search bar, the list of options are filtered and everything looks fine the on the console I see the error above. any advice on why everything continues to function properly but throws the error?

**Comment by basvandenberg** [comment]
I need more information to reproduce this error, could you provide some example code that reproduces this?

The error indicates that `null` is provided as argument to the `Diacritics.strip` function. This function is called twice from the `filter` functions in `option-list.ts` (line 119 and 120).

```
let l: string = Diacritics.strip(option.label).toUpperCase();
let t: string = Diacritics.strip(term).toUpperCase();
```
Which indicates that either `option.label` is `null`, meaning that one of your option labels is set to `null`. Or that somehow the search term is `null`, which I think is less likely. Could it be that one of the options in your options list has its label set to null?

**Comment by caleuanhopkins** [comment]
Hey, thanks for getting back. You are indeed correct. Just dumped out our list of 100+ options and can see 3 have null titles. The `IOptions` list is created by user submitted data so someone's been submitting invalid data on our system! Thanks for the response, we'll put some catches in to exclude options in the dropdown list that have null labels 👍
