### ISSUE TITLE
single select mode graphical issue ie9/ie10

### ISSUE THREAD

**Issue by gdisanto** [basvandenberg/ng-select#77]
There is a graphical issue on ie9/i10 when the component is used in single mode with the allowClear function enabled.
Since it's a graphical issue, an image is better than a thousand words: https://postimg.org/image/oc5ypdi7n/.

Everything seems to  work fine by the way.

**Comment by basvandenberg** [comment]
Thanks for raising this issue @gdisanto. I didn't get to test much on IE yet, every input on IE9/IE10 are more than welcome.

This looks like a browser support issue. I am using flexible boxes (CSS) which seem to be not supported in IE9 and IE10. I'll have a look at this.

**Comment by basvandenberg** [comment]
I've tested this on (emulated) IE9 and IE10, which worked as expected. Please let me know if you still have the same issue with the latest (beta.6) release.
