### ISSUE TITLE
How to set values in multiple input - Reactive forms

### ISSUE THREAD

**Issue by kresogalic8** [basvandenberg/ng-select#96]
Hey guys, I'm having problems with settings values which I get from the server. This is what I have in the code to set those values.

API request 

```
getAdministratorDetails() {

        this._api.send(urlValues.singleAdministrator, 'Post', {hash_id: this.adminId}).subscribe(
          res => {
              console.log('customer get', res);
              this.buildAdministrator(res.content.user);
              this.contentLoaded = true;
          },
          err => console.log(err)
        );
    }
```

Building the form

```
buildAdministrator(admin?: any) {
      if (admin) {
        this.adminForm = this._fb.group({
          username: admin.username,
          password: admin.password,
          email: admin.email,
          first_name: admin.first_name,
          last_name: admin.last_name,
          address: this._fb.group({
            street: admin.address.street,
            number: admin.address.number,
            post_code: admin.address.post_code,
            city: admin.address.city,
            country: admin.address.country
          }),
          oib: admin.oib,
          groups: admin.groups,
          contacts: this._fb.array([])
        });
        admin.contacts.length ? admin.contacts.forEach(contact => (<FormArray>this.adminForm.controls['contacts']).push(this.initContact(contact))) : this.initContact();
      } else {
        this.adminForm = this._fb.group({
          username: '',
          password: '',
          email: '',
          first_name: '',
          last_name: '',
          address: this._fb.group({
            street: '',
            number: '',
            post_code: '',
            city: '',
            country: ''
          }),
          oib: '',
          groups: ['', Validators.required],
          contacts: this._fb.array([
            this.initContact()
          ])
        });
      }
    }
```

What I tried is to hardcode values just to set them in input, but that also doesn't work. Every object has keys value and label. Like this: 

       ```
 this.adminForm.patchValue({groups: [
          {
            label: 'Krvitelji',
            value: '0'
          }
        ]});
```

**Comment by matthewhegarty** [comment]
Assign your options to a array variable, 

```
myOptions = {label: 'Krvitelji', value: '0'}
```

which you then bind in your html:

```
<ng-select [options]="myOptions" [multiple]="true" formControlName="adminForm">
</ng-select>
```

You can dynamically load the options from an API call.  I suggest you declare `adminForm` in `ngOnInit()` or constructor.

There are examples in the [source tree](https://github.com/basvandenberg/angular2-select/tree/master/demo), and [plunker](https://plnkr.co/edit/XlIsjaSdgaqHB0jLCS9z?p=preview)

**Comment by kresogalic8** [comment]
Hm I am doing this on ngOnInit()... Why should I declare adminForm onInit or constructor? I think that won't change anything. Look at the screenshot what I get from server and what I hardcoded in input

![screen shot 2017-02-07 at 2 29 16 pm](https://cloud.githubusercontent.com/assets/7289406/22693155/58609224-ed42-11e6-8710-c9bae8b74380.png)

**Comment by basvandenberg** [comment]
It would be helpful to see the template code as well. 

This looks more like a support request than an issue report. With questions please use stackoverflow or something similar.

**Comment by matthewhegarty** [comment]
Checkout this [plunker](https://plnkr.co/edit/kEeScf38NmheIaR6t49V) which populates options from HTTP GET.
